name = "PolynomialChaos"
uuid = "14459081-b74c-4d79-9595-5739a302c9fe"
authors = ["eiad-hamwi <ehamwi@bnl.gov>"]
version = "0.1.0"

[deps]
GTPSA = "b27dd330-f138-47c5-815b-40db9dd9b6e8"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[targets]
test = ["Test", "Plots"]

[weakdeps]
SciBmad = "7bf6e793-a2ec-421f-8700-d1465381ee80"
TypedTables = "9d95f2ec-7b3d-5a63-8d20-e2491e220bb9"

[extensions]
PolynomialChaosSciBmadExt = ["SciBmad", "TypedTables"]

[compat]
julia = "1.10"
GTPSA = "1.5"
